const router=require('express').Router();const bcrypt=require('bcryptjs');const User=require('../models/User');const Rating=require('../models/Rating');const Feedback=require('../models/Feedback');const Ticket=require('../models/Ticket');const Notification=require('../models/Notification');const {auth}=require('../middleware/auth');
router.get('/profile',auth,(req,res)=>res.json({user:{id:req.user._id.toString(),name:req.user.name,email:req.user.email,phone:req.user.phone||'',bio:req.user.bio||'',role:req.user.role}}));router.get('/favorites',auth,async(req,res)=>{const u=await User.findById(req.user._id).populate('favorites').lean();res.json({events:(u.favorites||[]).map(e=>({...e,id:e._id.toString()}))})});router.post('/favorites/:eventId',auth,async(req,res)=>{const u=await User.findById(req.user._id);const i=u.favorites.findIndex(x=>String(x)===req.params.eventId);if(i>=0){u.favorites.splice(i,1);await u.save();return res.json({saved:false})}u.favorites.push(req.params.eventId);await u.save();res.json({saved:true})});
router.get('/preferences',auth,(req,res)=>res.json(req.user.preferences||{}));router.put('/preferences',auth,async(req,res)=>{req.user.preferences={...(req.user.preferences||{}),...(req.body||{})};await req.user.save();res.json(req.user.preferences)});
router.put('/profile',auth,async(req,res)=>{req.user.name=req.body.name||req.user.name;req.user.phone=req.body.phone??req.user.phone;req.user.bio=req.body.bio??req.user.bio;await req.user.save();res.json({user:{id:req.user._id.toString(),name:req.user.name,email:req.user.email,phone:req.user.phone,bio:req.user.bio||'',role:req.user.role}})});
router.put('/password',auth,async(req,res)=>{try{const {currentPassword,newPassword,confirmPassword}=req.body||{};if(!currentPassword||!newPassword||!confirmPassword)return res.status(400).json({message:'All password fields are required'});if(newPassword.length<8)return res.status(400).json({message:'New password must be at least 8 characters'});if(newPassword!==confirmPassword)return res.status(400).json({message:'New passwords do not match'});const user=await User.findById(req.user._id);if(!user)return res.status(404).json({message:'Account not found'});const ok=await bcrypt.compare(currentPassword,user.passwordHash);if(!ok)return res.status(400).json({message:'Current password is incorrect'});if(currentPassword===newPassword)return res.status(400).json({message:'New password must be different from the current password'});user.passwordHash=await bcrypt.hash(newPassword,12);await user.save();res.json({ok:true,message:'Password changed successfully'})}catch(e){console.error('Password change error:',e);res.status(500).json({message:'Could not change password'})}});
router.get('/reviews/:eventId/mine',auth,async(req,res)=>{const row=await Feedback.findOne({eventId:req.params.eventId,userId:req.user._id}).lean();if(!row)return res.status(404).json({message:'No review yet'});res.json({id:row._id.toString(),rating:row.rating,comment:row.comment||'',createdAt:row.createdAt})});
router.post('/reviews/:eventId',auth,async(req,res)=>{try{const rating=Number(req.body.rating);const comment=String(req.body.comment||'').trim().slice(0,1000);if(rating<1||rating>5)return res.status(400).json({message:'Rating must be between 1 and 5'});const ticket=await Ticket.findOne({userId:req.user._id,eventId:req.params.eventId,status:{$in:['valid','used']}}).lean();if(!ticket)return res.status(403).json({message:'You can review an event only after booking a ticket'});const row=await Feedback.findOneAndUpdate({userId:req.user._id,eventId:req.params.eventId},{rating,comment},{upsert:true,new:true,setDefaultsOnInsert:true});res.json({id:row._id.toString(),rating:row.rating,comment:row.comment||'',createdAt:row.createdAt})}catch(err){res.status(400).json({message:err.message||'Could not save review'})}});
router.post('/ratings/:eventId',auth,async(req,res)=>{const value=Number(req.body.value);if(value<1||value>5)return res.status(400).json({message:'Rating must be 1-5'});res.json(await Rating.findOneAndUpdate({userId:req.user._id,eventId:req.params.eventId},{value},{upsert:true,new:true}))});
router.get('/notifications',auth,async(req,res)=>res.json(await Notification.find({userId:req.user._id}).sort({createdAt:-1}).limit(100).lean()));router.post('/notifications/:id/read',auth,async(req,res)=>{await Notification.updateOne({_id:req.params.id,userId:req.user._id},{$set:{read:true}});res.json({ok:true})});router.post('/notifications/read-all',auth,async(req,res)=>{await Notification.updateMany({userId:req.user._id,read:false},{$set:{read:true}});res.json({ok:true})});module.exports=router;
